Sprint 07
mhg77/MovieQuiz-ios pull request #6
Opened 2023-05-23 20:12 UTC by mhg77

add tests and make refactoring

2023-05-24 20:42 UTC, IBDesignable requested changes
Заметила ошибку в верстке сплеш-скрина: картинка плющится, если формат экрана отличается от картинки, нужно поправить contentMode

Также будет круто почеленджить себя и решить проблему с версткой для маленьких экранов: 

<img width="487" alt="Снимок экрана 2023-05-24 в 23 41 03" src="https://github.com/mhg77/MovieQuiz-ios/assets/121577115/b6a7c77d-f514-4ff0-8f87-9026c7964fac">

2023-05-24 20:42 UTC, IBDesignable commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    init(delegate: MovieQuizViewControllerProtocol) {
```suggestion
    private weak var delegate: MovieQuizViewControllerProtocol?
    
    init(delegate: MovieQuizViewControllerProtocol) {
```

2023-05-24 20:42 UTC, IBDesignable commented on MovieQuiz/Presentation/AlertPresenter.swift
> +        let vc = delegate as! UIViewController
Любой избыточный форс анврап и форс каст будет считаться ошибкой. Например как здесь.

В данном случае переданный протокол MovieQuizViewControllerProtocol  не используется ни в одном месте: функции его не зайдействованы в этом презентере.

Значит надо было передать тот тип, который позволит тебе решить задачу: то есть имеющий в реализации метод `present(:, animated:, completion)`.

Можно прям такой протокол написать, но мне кажется это избыточно: достаточно честно сохранять ссылку на UIViewController. Только в таком случае имя у переменной лучше изменить с делегата на viewController. Потому что делегировать тут практически нечего)

2023-05-24 20:42 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +
В любой презентационной архитектуре (MVP, VIPER, MVVM) будет сущность отвечающая за логику – как здесь прзентер. Такие сущности не должны знать ничего про UIKit. Его нужно отсюда убрать, затем проверить, что никакая ui-китовая сущность в прзезентере не используется.

2023-05-24 20:42 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        alertPresenter = AlertPresenter(delegate: viewController)
алерт презентер можно инициализировать от viewController в самом вью контроллере: и дальше его либо сохранять во вью-контроллере, как и главный презентер, либо передавать в MovieQuizPresenter в инициализатор. 

Так не придется лишний раз кастить, как выше уже описала

2023-05-24 20:42 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    }
обычно используем такой порядок: сначала перечисляем свойства класса, затем функции. 
При этом также делим на приватные и публичные блоки. 
Функции перечисляют в таком порядке: `init`ы, `override`ы, блоки публичных и приватных функций, и далее блок c аннтотацией `@IBAction`(уместно для вьюх)

2023-05-24 20:42 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        alertPresenter?.show(alertModel: model)
очень хорошо что ошибка и результат  обе показываются через презентер - ты переиспользуешь написанное решение)

2023-05-25 06:15 UTC, mhg77 commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +
Тогда получается что в самом учебнике ошибка(

2023-05-25 06:17 UTC, mhg77 commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +
![image](https://github.com/mhg77/MovieQuiz-ios/assets/98677259/44610b7b-ba89-444f-bfcf-da1ce9f4861d)

2023-05-25 07:24 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +
Спасибо! передам команде! ❤️

В таком случае лучше поступить так: отдавать вью-контроллерру model.image как Data, пусть уже на вью-контроллере создается UIImage – так реализация будет чистой.

Ну и если ты не захочешь это исправлять, потому что в учебнике показали именно так – я пойму и зачту, потому что косяк не твой) Мне главное чтобы суть замечания была ясной и ты такой ошибки не допустил в следующих работах)

2023-05-25 09:19 UTC, mhg77 commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +
Поправил. Убрал UIKit из презентора и из моделей :D

2023-05-25 17:59 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.image = UIImage(data: step.imageData)
супер!

2023-05-25 18:24 UTC, merged